version: "3.8"

services:
  db:
    image: postgres:16
    # restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    # ports:
    #   - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: account_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["./main", "-host=0.0.0.0", "-port=8080"]

volumes:
  db_data:
