version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: account_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./main", "-host=0.0.0.0", "-port=8080"]

volumes:
  db_data:
