package main

import (
	"fmt"
	"supardi98/service-account-api/config"
	"supardi98/service-account-api/database"
	"supardi98/service-account-api/docs"
	"supardi98/service-account-api/middlewares"
	"supardi98/service-account-api/routes"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/log"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "supardi98/service-account-api/docs"
)

// @title Service Account API
// @version 1.0
// @description This is a sample swagger for Fiber
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email fiber@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath /
func main() {
	log.Info("Memulai aplikasi...")
	config.LoadConfig()

	docs.SwaggerInfo.Host = config.APP_URL

	// Connect to database
	db := database.Connect()

	app := fiber.New(fiber.Config{
		ErrorHandler: middlewares.ErrorHandler,
	})

	app.Use(logger.New())
	app.Use(cors.New())

	// Setup routes
	routes.SetupAuthRoutes(app, db)
	routes.SetupBalanceRoutes(app, db)

	app.Get("/swagger/*", swagger.HandlerDefault)

	// Mengatur alamat server
	address := fmt.Sprintf("%s:%s", config.Host, config.Port)

	log.Info(fmt.Sprintf("Aplikasi berjalan pada host %s dan port %s", config.Host, config.Port))
	log.Fatal(app.Listen(address))
}
